services:
  db:
    image: postgres:17
    container_name: uniqueue-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432

volumes:
  postgres_data:
