"""live update queries

Revision ID: 106a168e210a
Revises: 245ad11dcd74
Create Date: 2026-08-09 23:24:46.612220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106a168e210a'
down_revision: Union[str, Sequence[str], None] = '245ad11dcd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues', sa.Column('last_msg_id', sa.BigInteger(), nullable=True))
    op.add_column('queues', sa.Column('last_chat_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'last_chat_id')
    op.drop_column('queues', 'last_msg_id')
    # ### end Alembic commands ###
