"""add notified_next_id

Revision ID: 186002678e4e
Revises: 7ad7e3559cb2
Create Date: 2026-08-13 01:54:13.942316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '186002678e4e'
down_revision: Union[str, Sequence[str], None] = '7ad7e3559cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues', sa.Column('notified_next_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'notified_next_id')
    # ### end Alembic commands ###
