"""telegram_chat_id in rooms

Revision ID: 245ad11dcd74
Revises: 791496739e58
Create Date: 2026-08-09 17:00:19.282454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245ad11dcd74'
down_revision: Union[str, Sequence[str], None] = '791496739e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'rooms', ['telegram_chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_column('rooms', 'telegram_chat_id')
    # ### end Alembic commands ###
