"""add room name creator constraint

Revision ID: 27d5e573b8e2
Revises: b5025c7128fc
Create Date: 2026-08-05 20:17:30.894610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d5e573b8e2'
down_revision: Union[str, Sequence[str], None] = 'b5025c7128fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_name_creator_uc', 'rooms', ['name', 'creator_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_creator_uc', 'rooms', type_='unique')
    # ### end Alembic commands ###
