"""add current_speaker

Revision ID: 7ad7e3559cb2
Revises: 106a168e210a
Create Date: 2026-08-13 01:34:54.416045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad7e3559cb2'
down_revision: Union[str, Sequence[str], None] = '106a168e210a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues', sa.Column('current_speaker_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'current_speaker_id')
    # ### end Alembic commands ###
