"""add cascade delete

Revision ID: aaf59fe9e68b
Revises: 733466d791f2
Create Date: 2026-08-07 18:23:35.514098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf59fe9e68b'
down_revision: Union[str, Sequence[str], None] = '733466d791f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('queue_entries_queue_id_fkey'), 'queue_entries', type_='foreignkey')
    op.create_foreign_key(None, 'queue_entries', 'queues', ['queue_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('queues_room_id_fkey'), 'queues', type_='foreignkey')
    op.create_foreign_key(None, 'queues', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queues', type_='foreignkey')
    op.create_foreign_key(op.f('queues_room_id_fkey'), 'queues', 'rooms', ['room_id'], ['id'])
    op.drop_constraint(None, 'queue_entries', type_='foreignkey')
    op.create_foreign_key(op.f('queue_entries_queue_id_fkey'), 'queue_entries', 'queues', ['queue_id'], ['id'])
    # ### end Alembic commands ###
