"""Cascade deleting

Revision ID: f4eac69090bc
Revises: 27d5e573b8e2
Create Date: 2026-08-05 21:11:17.270331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4eac69090bc'
down_revision: Union[str, Sequence[str], None] = '27d5e573b8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('room_members_room_id_fkey'), 'room_members', type_='foreignkey')
    op.create_foreign_key(None, 'room_members', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.create_foreign_key(op.f('room_members_room_id_fkey'), 'room_members', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
